"""初始化创建表资产和表版本

Revision ID: 9706bff97cc3
Revises: 
Create Date: 2026-06-16 21:45:34.344244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9706bff97cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('table_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.Enum('UPLOAD_FILE', 'WORKFLOW_OUTPUT', name='sourcetype'), nullable=False),
    sa.Column('storage_type', sa.Enum('LOCAL_CSV', name='storagetype'), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_uri', name='uq_table_asset_storage_uri'),
    sa.UniqueConstraint('table_asset_id', 'version_number', name='uq_table_asset_version_number')
    )
    op.create_index(op.f('ix_table_versions_table_asset_id'), 'table_versions', ['table_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_versions_table_asset_id'), table_name='table_versions')
    op.drop_table('table_versions')
    op.drop_table('table_assets')
    # ### end Alembic commands ###
