"""调整name字段长度

Revision ID: cdb19e894181
Revises: ced0d48360d3
Create Date: 2026-06-27 17:54:51.517598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb19e894181'
down_revision: Union[str, Sequence[str], None] = 'ced0d48360d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_assets', 'name',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('workflows', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('table_assets', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
