[project]
name = "featuremaker-api"
version = "0.1.0"
requires-python = ">=3.11,<4.0"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "pydantic-settings",
    "sqlalchemy",
    "psycopg[binary]>=3.3.4,<4.0.0",
    "alembic",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx2",
]


[tool.fastapi]
entrypoint = "featuremaker.main:app"
